#!/usr/bin/env python3
"""Writes signature-base.json.

Deliberately independent of the Rust implementation: the expected `@signature-params` values are
written by hand as canonical Structured Fields serializations, and the bases and hashes are
assembled here following RFC 9421 §2.5. Run from the repository root:

    python3 test-vectors/generate_signature_base.py
"""

import base64
import hashlib
import json

CANONICAL = '("@method" "@scheme" "@authority" "@path" "@query" "content-digest" "integrity-token");created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg==";alg="world-integrity-ios-v1"'
FLAMINGO = '("@method" "@scheme" "@authority" "@path" "@query" "content-digest" "integrity-token");created=1790000000;nonce="q83vEjRWeJCrze8SNFZ4kA==";alg="world-integrity-ios-v1"'
EMPTY_DIGEST = "sha-256=:" + base64.b64encode(hashlib.sha256(b"").digest()).decode() + ":"

REFERENCE = {
    "@method": "POST",
    "@scheme": "https",
    "@authority": "api.example.com",
    "@path": "/v3/face-auth/config",
    "@query": "?",
    "content-digest": "sha-256=:abc123:",
    "integrity-token": "eyJhbGciOi.test",
}
WEBSOCKET = {
    "@method": "GET",
    "@scheme": "https",
    "@authority": "flamingo-verifier.toolsforhumanity.com",
    "@path": "/v1/matches",
    "@query": "?",
    "content-digest": EMPTY_DIGEST,
    "integrity-token": "eyJhbGciOiJFUzI1NiJ9.e30.c2ln",
}


def case(name, signature_input, components, params, note=None):
    order = [item.strip('"') for item in params[1 : params.index(")")].split(" ")]
    lines = [f'"{c}": {components[c]}' for c in order]
    lines.append(f'"@signature-params": {params}')
    base = "\n".join(lines)
    entry = {
        "name": name,
        "signature_input": signature_input,
        "components": components,
        "expected_signature_params": params,
        "expected_base": base,
        "expected_client_data_hash": base64.b64encode(hashlib.sha256(base.encode()).digest()).decode(),
    }
    if note:
        entry["note"] = note
    return entry


def digest(body):
    return "sha-256=:" + base64.b64encode(hashlib.sha256(body).digest()).decode() + ":"


vectors = {
    "description": (
        "RFC 9421 signature bases for the TFH integrity profile. `@signature-params` is the "
        "canonical Structured Fields serialization of the parsed Signature-Input member "
        "(RFC 9421 §3.2 step 7), never the raw wire substring. Generated by "
        "generate_signature_base.py."
    ),
    "signature_base": [
        case("reference fixture (go-sonic, oxide, app-backend-app-config)", "integrity=" + CANONICAL, REFERENCE, CANONICAL),
        case("flamingo websocket upgrade", "integrity=" + FLAMINGO, WEBSOCKET, FLAMINGO),
        case(
            "extra spaces between components",
            "integrity=" + CANONICAL.replace('" "', '"   "'),
            REFERENCE,
            CANONICAL,
            "Valid Structured Fields whitespace does not change the base.",
        ),
        case(
            "spaces inside the inner list",
            "integrity=" + CANONICAL.replace('("@method"', '(  "@method"').replace('token")', 'token"  )'),
            REFERENCE,
            CANONICAL,
        ),
        case(
            "spaces after parameter semicolons",
            "integrity=" + CANONICAL.replace(";", "; "),
            REFERENCE,
            CANONICAL,
        ),
        case("leading and trailing whitespace", "  integrity=" + CANONICAL + "  ", REFERENCE, CANONICAL),
        case(
            "integer with leading zeros",
            "integrity=" + CANONICAL.replace("created=1710000000", "created=0001710000000"),
            REFERENCE,
            CANONICAL,
            "Integers serialize without leading zeros.",
        ),
        case(
            "parameters in another order",
            'integrity=("@method" "@scheme" "@authority" "@path" "@query" "content-digest" "integrity-token");alg="world-integrity-ios-v1";created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg=="',
            REFERENCE,
            '("@method" "@scheme" "@authority" "@path" "@query" "content-digest" "integrity-token");alg="world-integrity-ios-v1";created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg=="',
            "Order is preserved, so the base differs from the default order and still verifies.",
        ),
        case(
            "components in another order",
            'integrity=("integrity-token" "@path" "@method" "@scheme" "@authority" "@query" "content-digest");created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg==";alg="world-integrity-ios-v1"',
            REFERENCE,
            '("integrity-token" "@path" "@method" "@scheme" "@authority" "@query" "content-digest");created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg==";alg="world-integrity-ios-v1"',
        ),
        case(
            "android get with a query",
            'integrity=("@method" "@scheme" "@authority" "@path" "@query" "content-digest" "integrity-token");created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg==";alg="world-integrity-android-v1"',
            {**REFERENCE, "@method": "GET", "@path": "/api/v1/data/custody", "@query": "?sub=alice&x=%2F", "content-digest": EMPTY_DIGEST},
            '("@method" "@scheme" "@authority" "@path" "@query" "content-digest" "integrity-token");created=1710000000;nonce="MDEyMzQ1Njc4OWFiY2RlZg==";alg="world-integrity-android-v1"',
        ),
    ],
    "derived_components": [
        {"name": "websocket upgrade", "target": "/v1/matches", "body_base64": "", "expected": {"@path": "/v1/matches", "@query": "?", "content-digest": EMPTY_DIGEST}},
        {"name": "empty query", "target": "/v1/config?", "body_base64": "", "expected": {"@path": "/v1/config", "@query": "?", "content-digest": EMPTY_DIGEST}},
        {"name": "percent-encoded path and query", "target": "/v1/a%20b?x=%2F&y", "body_base64": "", "expected": {"@path": "/v1/a%20b", "@query": "?x=%2F&y", "content-digest": EMPTY_DIGEST}},
        {
            "name": "json body",
            "target": "/v1/config?sub=alice",
            "body_base64": base64.b64encode(b'{"hello":"world"}').decode(),
            "expected": {"@path": "/v1/config", "@query": "?sub=alice", "content-digest": digest(b'{"hello":"world"}')},
        },
    ],
}

with open("test-vectors/signature-base.json", "w") as out:
    json.dump(vectors, out, indent=2)
    out.write("\n")
